name: Notify website update

on:
  push:
    branches:
      - main   # Change if your branch is different

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send update email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}

          subject: Website Updated
          to: ${{ secrets.EMAIL_TO }}
          from: Website Updates (Automated) <${{ secrets.EMAIL_FROM }}>

          body: |
            The website has been updated.
            You can view it here:
            https://ajkcm14.github.io/20240808/
